CREATE DATABASE IF NOT EXISTS odontologia_ti_26;
USE odontologia_ti_26;

CREATE TABLE IF NOT EXISTS pacientes(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
	RG VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(11) NOT NULL,
    DATA_NASC DATE NOT NULL,
    CONVENIO VARCHAR(200) NOT NULL
);

CREATE INDEX PACIENTES_IDX ON pacientes (CPF); # otimiza buscas baseadas em cpf

CREATE TABLE IF NOT EXISTS endereco_pacientes(
	FK_PACIENTE_ID INT NOT NULL PRIMARY KEY, # PK E FK (deve ter inserção)
	RUA VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,

	FOREIGN KEY (FK_PACIENTE_ID) REFERENCES pacientes(ID)
);

CREATE TABLE IF NOT EXISTS dentistas(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
	RG VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(11) NOT NULL,
    DATA_NASC DATE NOT NULL,
    CRO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS endereco_dentistas(
	FK_DENTISTA_ID INT NOT NULL PRIMARY KEY, # PK E FK (deve ter inserção)
	RUA VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,

	FOREIGN KEY (FK_DENTISTA_ID) REFERENCES dentistas(ID)
);

CREATE TABLE IF NOT EXISTS agendamentos(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_PACIENTE_ID INT NOT NULL,
    FK_DENTISTA_ID INT NOT NULL,
    DIA_HORA DATETIME NOT NULL,

    FOREIGN KEY (FK_DENTISTA_ID) REFERENCES pacientes(ID),
    FOREIGN KEY (FK_DENTISTA_ID) REFERENCES dentistas(ID)
);

CREATE INDEX AGENDAMENTO_IDX ON agendamentos(FK_PACIENTE_ID, FK_DENTISTA_ID);